# Generated by Django 4.0.2 on 2022-03-01 07:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import starline.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Имя отправителя отзыва')),
                ('numbers_phone', models.CharField(max_length=17, validators=[starline.models.validate_phone], verbose_name='Номер телефона')),
                ('body', models.TextField(verbose_name='Содержимое комментария')),
                ('pub_data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата комментария')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ('pub_data',),
            },
        ),
        migrations.CreateModel(
            name='NumberPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='', verbose_name='Логотип оператора связи')),
                ('numbers', models.CharField(max_length=50, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Моб.номер',
                'verbose_name_plural': 'Моб.номера',
            },
        ),
        migrations.CreateModel(
            name='OurWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='', verbose_name='Фотографии работ')),
                ('video_url', models.CharField(max_length=250, verbose_name='Видео работ')),
            ],
        ),
        migrations.CreateModel(
            name='Warranty_Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Гарантия и поддержка')),
            ],
            options={
                'verbose_name': 'Гарантия',
                'verbose_name_plural': 'Гарантии',
            },
        ),
        migrations.CreateModel(
            name='Answer_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Имя')),
                ('body', models.TextField(verbose_name='Ответ на отзыв')),
                ('pub_data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата ответа на комментарий')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='starline.comment', verbose_name='Содержимое отзыва')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы на отзывы',
            },
        ),
    ]
