<<<<<<< HEAD
# Generated by Django 4.0.2 on 2022-03-02 11:37
=======
# Generated by Django 4.0.2 on 2022-03-02 11:45
>>>>>>> origin/master

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название магазина')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес магазина')),
                ('phone1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер телефона1')),
                ('phone2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер телефона2')),
                ('phone_service', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер телефона сервиса')),
                ('email', models.CharField(max_length=100, verbose_name='Электронная почта')),
                ('social_info', models.CharField(blank=True, max_length=100, null=True, verbose_name='Социальная сеть')),
                ('time_work1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Время работы (будни)')),
                ('time_work2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Время работы (выходные)')),
                ('maps', models.TextField(blank=True, null=True, verbose_name='Расположение на карте')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.CharField(blank=True, max_length=100, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('published', models.BooleanField(default=True, verbose_name='Обработано')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
            },
        ),
    ]
