# Generated by Django 4.0.2 on 2022-03-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starline', '0002_contacts_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(blank=True, max_length=20, null=True, unique=True, verbose_name='Слаг')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название ')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True, verbose_name='Слаг')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Цена без установки')),
                ('price_install', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Цена с установкой')),
                ('time_first', models.CharField(blank=True, max_length=10, null=True, verbose_name='Время установки 1')),
                ('time_second', models.CharField(blank=True, max_length=10, null=True, verbose_name='Время установки 2')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d/', verbose_name='Картинка')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('category', models.ManyToManyField(related_name='cat', to='starline.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ('-id',),
            },
        ),
    ]
